#!/bin/bash

WASMD_DATA="$(pwd)/data"


echo "Generating rly configurations..."
rly config init
rly config add-chains configs/wasmd/10chains/chains

SEED0=$(jq -r '.mnemonic' $WASMD_DATA/ibc-0/testkey_seed.json)
SEED1=$(jq -r '.mnemonic' $WASMD_DATA/ibc-1/testkey_seed.json)
SEED2=$(jq -r '.mnemonic' $WASMD_DATA/ibc-2/testkey_seed.json)
SEED3=$(jq -r '.mnemonic' $WASMD_DATA/ibc-3/testkey_seed.json)
SEED4=$(jq -r '.mnemonic' $WASMD_DATA/ibc-4/testkey_seed.json)
SEED5=$(jq -r '.mnemonic' $WASMD_DATA/ibc-5/testkey_seed.json)
SEED6=$(jq -r '.mnemonic' $WASMD_DATA/ibc-6/testkey_seed.json)
SEED7=$(jq -r '.mnemonic' $WASMD_DATA/ibc-7/testkey_seed.json)
SEED8=$(jq -r '.mnemonic' $WASMD_DATA/ibc-8/testkey_seed.json)
SEED9=$(jq -r '.mnemonic' $WASMD_DATA/ibc-9/testkey_seed.json)

echo "Key $(rly keys restore ibc-0 testkey "$SEED0") imported from ibc-0 to relayer..."
echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
echo "Key $(rly keys restore ibc-2 testkey "$SEED2") imported from ibc-2 to relayer..."
echo "Key $(rly keys restore ibc-3 testkey "$SEED3") imported from ibc-3 to relayer..."
echo "Key $(rly keys restore ibc-4 testkey "$SEED4") imported from ibc-4 to relayer..."
echo "Key $(rly keys restore ibc-5 testkey "$SEED5") imported from ibc-5 to relayer..."
echo "Key $(rly keys restore ibc-6 testkey "$SEED6") imported from ibc-6 to relayer..."

wasmd keys delete ibc-7 -y &> /dev/null || true
wasmd keys delete ibc-8 -y &> /dev/null || true
wasmd keys delete ibc-9 -y &> /dev/null || true


echo "Key $(rly keys restore ibc-7 testkey "$SEED7") imported from ibc-7 to relayer..."
echo "Key $(rly keys restore ibc-8 testkey "$SEED8") imported from ibc-8 to relayer..."
echo "Key $(rly keys restore ibc-9 testkey "$SEED9") imported from ibc-9 to relayer..."

rly config add-paths configs/wasmd/10chains/paths

set +x

